In [ ]:
#Q1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

import numpy as np

arr = np.random.randint(1, 101, size=(3, 3))

interchanged_arr = arr.T

print("Original Array:")
print(arr)
print("\nInterchanged Array:")
print(interchanged_arr)


Original Array:
[[86 75 27]
 [47 71 99]
 [90 75 12]]

Interchanged Array:
[[86 47 90]
 [75 71 75]
 [27 99 12]]


In [ ]:
#Q2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

import numpy as np

arr = np.arange(10)

arr_2x5 = arr.reshape(2, 5)
arr_5x2 = arr.reshape(5, 2)

print("Original Array:")
print(arr)
print("\n2x5 Array:")
print(arr_2x5)
print("\n5x2 Array:")
print(arr_5x2)

Original Array:
[0 1 2 3 4 5 6 7 8 9]

2x5 Array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

5x2 Array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
#Q3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

import numpy as np

arr = np.random.rand(4, 4)

bordered_arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)

print("Original Array:")
print(arr)
print("\nBordered Array:")
print(bordered_arr)


Original Array:
[[0.05967552 0.40352227 0.92856183 0.55263641]
 [0.29136385 0.16038455 0.63333364 0.00574734]
 [0.24747162 0.18696648 0.7190077  0.16116878]
 [0.96134005 0.37786842 0.70048617 0.72913997]]

Bordered Array:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.05967552 0.40352227 0.92856183 0.55263641 0.        ]
 [0.         0.29136385 0.16038455 0.63333364 0.00574734 0.        ]
 [0.         0.24747162 0.18696648 0.7190077  0.16116878 0.        ]
 [0.         0.96134005 0.37786842 0.70048617 0.72913997 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [ ]:
#Q4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

import numpy as np

arr = np.arange(10, 61, 5)

print(arr)


[10 15 20 25 30 35 40 45 50 55 60]


In [ ]:
#Q5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

import numpy as np

arr = np.array(['PythOn', 'nUmPy', 'PandaS'])

uppercase_arr = np.char.upper(arr)
lowercase_arr = np.char.lower(arr)
titlecase_arr = np.char.title(arr)

print("Original Array:")
print(arr)
print("\nUppercase Array:")
print(uppercase_arr)
print("\nLowercase Array:")
print(lowercase_arr)
print("\nTitlecase Array:")
print(titlecase_arr)


Original Array:
['PythOn' 'nUmPy' 'PandaS']

Uppercase Array:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase Array:
['python' 'numpy' 'pandas']

Titlecase Array:
['Python' 'Numpy' 'Pandas']


In [1]:
#Q6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

import numpy as np
a=np.array(['hello', 'world', 'numpy', 'array'])
for word in a:
    spaced_word = ' '.join(word)
    print(spaced_word)

h e l l o
w o r l d
n u m p y
a r r a y


In [6]:
#Q7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])
addition=a+b
subtraction=a-b
multiplication=a*b
division=a/b
print(a)
print(b)
print("Addition of array:\n",addition)
print("Subtraction of arrays:\n",subtraction)
print("Multiplication of two 2d arrays:\n",multiplication)
print("Division of two 2d arrays:\n",division)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
Addition of array:
 [[ 8 10 12]
 [14 16 18]]
Subtraction of arrays:
 [[-6 -6 -6]
 [-6 -6 -6]]
Multiplication of two 2d arrays:
 [[ 7 16 27]
 [40 55 72]]
Division of two 2d arrays:
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [7]:
#Q8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

import numpy as np
a=np.eye(5)
print(a)
print("Diagonal elements:\n",np.diag(a))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal elements:
 [1. 1. 1. 1. 1.]


In [8]:
#Q9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

import numpy as np
a=np.random.randint(0,1000,100)
print(a)
for i in a:
    if i>1:
        for j in range(2,i):
            if i%j==0:
                break
        else:
            print(i,end=' ')


[753 682 496 755 959 377 980 133 887 904 734 901 233 995 450 553 747 755
 959 981 661 101 719 441 122 883 389 146  38 742 141 891 319 316 889 319
 837 955 392 910 149 318 880 273 572 686  34 518 511   5 718 209 325 129
 142 913 966  84 824 975 858 999 176 849 925 971 635 763 785 479 384 400
 575 254 672 542 450 943 887 660  46 505 722 306 702 174 662 189 583 975
 435 849 595 319 590 264 338  68 987 356]
887 233 661 101 719 883 389 149 5 971 479 887 

In [9]:
#Q10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

import numpy as np
daily_temperature = np.random.randint(22, 25, 28)
print("Daily Temperatures:", daily_temperature)
weekly_temperatures = daily_temperature.reshape(-1, 7)
print(weekly_temperatures)
weekly_average = np.mean(weekly_temperatures, axis=1)
print("Weekly Averages:", weekly_average)
overall_average = np.mean(daily_temperature)
print("Overall Monthly Average:", overall_average)


Daily Temperatures: [24 23 24 23 24 23 23 22 22 23 23 23 24 22 23 22 23 23 22 22 22 23 24 22
 24 22 24 23]
[[24 23 24 23 24 23 23]
 [22 22 23 23 23 24 22]
 [23 22 23 23 22 22 22]
 [23 24 22 24 22 24 23]]
Weekly Averages: [23.42857143 22.71428571 22.42857143 23.14285714]
Overall Monthly Average: 22.928571428571427
